services:
  repocket:
    container_name: rocker
    build: .
    image: repocket-custom:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      RP_EMAIL: ${RP_EMAIL}
      RP_API_KEY: ${RP_API_KEY}
